### Import Necessary Libraries

In [8]:
from pandas_datareader import data, wb
import pandas as pd
import numpy as np
import datetime
%matplotlib inline

## Create date Variables

In [11]:
start= datetime.datetime(2006,1,1)
end=   datetime.datetime(2016,1,1)

In [12]:
###  Get Remote Data
## Bank Of America  BAC
BAC = data.DataReader('BAC','yahoo',start,end)
## CitiGroup  C
C = data.DataReader('C','yahoo',start,end)
## Goldman Sachs GS
GS = data.DataReader('GS','yahoo',start,end)
##JPMorgan Chase  JPM
JPM = data.DataReader('JPM','yahoo',start,end)
##Morgan Stanley  MS
MS = data.DataReader('MS','yahoo',start,end)
## Wells Fargo  WFC
WFC = data.DataReader('WFC','yahoo',start,end)

### CREATE A LIST OF STOCK TICKER SYMBOLS (AS STRINGS) IN ALPHABETICAL ORDER, AND CALL THE LIST TICKERS

In [14]:
tickers = ['BAC','C','GS','JPM','MS','WFC']

### Use pd.cocat to concatenate the bank dataframes into a single dataframe called bank_stocks

In [16]:
bank_stocks = pd.concat([BAC,C,GS,JPM,MS,WFC], axis=1, keys=tickers)

### Check the head of the bank_stocks dataframe

In [24]:
bank_stocks.columns.names =(['ticker','stock info'])

In [25]:
bank_stocks.head()

ticker            BAC                                                          \
stock info       High        Low       Open      Close      Volume  Adj Close
Date
2006-01-03  47.180000  46.150002  46.919998  47.080002  16296700.0  35.523922
2006-01-04  47.240002  46.450001  47.000000  46.580002  17757900.0  35.146645
2006-01-05  46.830002  46.320000  46.580002  46.639999  14970700.0  35.191933
2006-01-06  46.910000  46.349998  46.799999  46.570000  12599800.0  35.139107
2006-01-09  46.970001  46.360001  46.720001  46.599998  15619400.0  35.161732

ticker               C                                      ...         MS  \
stock info        High         Low        Open       Close  ...       Open
Date                                                        ...
2006-01-03  493.799988  481.100006  490.000000  492.899994  ...  57.169998
2006-01-04  491.000000  483.500000  488.600006  483.799988  ...  58.700001
2006-01-05  487.799988  484.000000  484.399994  486.200012  ...  58.549999
2006-01-06  489.000000  482.000000  488.799988  486.200012  ...  58.770000
2006-01-09  487.399994  483.000000  486.000000  483.899994  ...  58.630001

ticker                                             WFC                        \
stock info      Close     Volume  Adj Close       High        Low       Open
Date
2006-01-03  58.310001  5377000.0  38.006454  31.975000  31.195000  31.600000
2006-01-04  58.349998  7977800.0  38.032536  31.820000  31.365000  31.799999
2006-01-05  58.509998  5778000.0  38.136818  31.555000  31.309999  31.500000
2006-01-06  58.570000  6889800.0  38.175922  31.775000  31.385000  31.580000
2006-01-09  59.189999  4144500.0  38.580029  31.825001  31.555000  31.674999

ticker
stock info      Close      Volume  Adj Close
Date
2006-01-03  31.900000  11016400.0  21.045347
2006-01-04  31.530001  10870000.0  20.801256
2006-01-05  31.495001  10158000.0  20.778162
2006-01-06  31.680000   8403800.0  20.900213
2006-01-09  31.674999   5619600.0  20.896914

[5 rows x 36 columns]

## EDA Exporatory Data Analysis

### Max Stock Close price for each of the banks through the period

In [34]:
### Using for loop
for tick in tickers:
    print(tick,bank_stocks[tick]['Close'].max())

BAC 54.900001525878906
C 564.0999755859375
GS 247.9199981689453
JPM 70.08000183105469
MS 89.30000305175781
WFC 58.52000045776367

In [35]:
### Using Pandas cross section xs()
bank_stocks.xs(key='Close', axis=1, level='stock info').max()

ticker
BAC     54.900002
C      564.099976
GS     247.919998
JPM     70.080002
MS      89.300003
WFC     58.520000
dtype: float64

In [36]:
### Create a new empty Returns dataframe

In [38]:
returns = pd.DataFrame()

In [40]:
### Create a forloop that that goes for each Stock ticker creates this returns column in the returns datframe

In [42]:
for tick in tickers:
    returns[tick + ' Return'] = bank_stocks[tick]['Close'].pct_change()

In [43]:
returns

            BAC Return  C Return  GS Return  JPM Return  MS Return  WFC Return
Date
2006-01-03         NaN       NaN        NaN         NaN        NaN         NaN
2006-01-04   -0.010620 -0.018462  -0.013812   -0.014183   0.000686   -0.011599
2006-01-05    0.001288  0.004961  -0.000393    0.003029   0.002742   -0.001110
2006-01-06   -0.001501  0.000000   0.014169    0.007046   0.001025    0.005874
2006-01-09    0.000644 -0.004731   0.012030    0.016242   0.010586   -0.000158
2006-01-10   -0.008369  0.003100   0.012578    0.001475   0.000507   -0.000789
2006-01-11   -0.002380  0.009065  -0.000454   -0.000737   0.005910    0.005213
2006-01-12   -0.006508  0.001021   0.002122   -0.018428  -0.001679   -0.011630
2006-01-13    0.000000 -0.002243   0.007637   -0.000751  -0.001513    0.005724
2006-01-17   -0.010699 -0.010016  -0.005028   -0.005260  -0.009599   -0.010277
2006-01-18   -0.001104 -0.001445  -0.001659   -0.010829  -0.006121    0.015974
2006-01-19   -0.002651 -0.008685   0.010954   -0.005601   0.015398   -0.015566
2006-01-20   -0.021046 -0.046934  -0.017785   -0.025858  -0.025274   -0.017729
2006-01-23   -0.005205  0.006785   0.010879    0.005782   0.010890    0.001789
2006-01-24    0.006369  0.000217   0.000978   -0.004181   0.003591   -0.000325
2006-01-25    0.008816  0.004782   0.004211    0.009709   0.008179    0.006657
2006-01-26    0.006050  0.016872   0.028751    0.028846   0.013520    0.009194
2006-01-27   -0.002227 -0.002978   0.011208    0.004041   0.013507    0.002078
2006-01-30   -0.007143 -0.001067   0.006693    0.002516  -0.001810   -0.003668
2006-01-31   -0.005621 -0.005126   0.009866   -0.002509   0.012856   -0.001761
2006-02-01   -0.006331 -0.005367   0.003257    0.003270   0.006184   -0.008339
2006-02-02   -0.011604 -0.024822   0.005716    0.002758  -0.009057   -0.008732
2006-02-03   -0.008057 -0.002656   0.001544   -0.011503   0.002775   -0.004241
2006-02-06    0.006498  0.002441   0.000560   -0.002277   0.004720    0.000164
2006-02-07    0.002767 -0.002657  -0.023386   -0.004564  -0.019440    0.001310
2006-02-08    0.004139  0.006881   0.011901    0.008660   0.012225    0.003272
2006-02-09    0.003664  0.009480  -0.002055    0.004293  -0.001469   -0.001631
2006-02-10    0.002053  0.003713  -0.000284    0.003772  -0.014220    0.008166
2006-02-13   -0.005009 -0.006092  -0.008238   -0.003757  -0.008290   -0.001296
2006-02-14    0.010526  0.009632   0.015252    0.008298   0.004347    0.016221
...                ...       ...        ...         ...        ...         ...
2015-11-18    0.024110  0.027856   0.016214    0.019961   0.019649    0.012918
2015-11-19   -0.008408  0.001455  -0.003253    0.003114  -0.002336    0.005389
2015-11-20   -0.002261 -0.005630  -0.008082   -0.001774  -0.007609   -0.002680
2015-11-23   -0.010198 -0.008584  -0.011908   -0.009772  -0.007962   -0.003941
2015-11-24    0.000000 -0.001842  -0.002749   -0.001495  -0.001486   -0.005755
2015-11-25   -0.001717 -0.001846   0.002544    0.001198   0.000595   -0.001085
2015-11-27    0.002294  0.002404   0.006979    0.004637   0.005058    0.003079
2015-11-30   -0.002860 -0.002214  -0.002363   -0.007295   0.015394   -0.005236
2015-12-01    0.021801  0.014605   0.016051    0.013947   0.028280    0.011071
2015-12-02   -0.010668 -0.013484  -0.014554   -0.014051  -0.010774   -0.011309
2015-12-03   -0.018161 -0.011637  -0.026595   -0.012901  -0.012611   -0.015977
2015-12-04    0.028902  0.029527   0.025864    0.031763   0.025254    0.027122
2015-12-07   -0.014607 -0.012525  -0.023685   -0.013109  -0.018120   -0.004491
2015-12-08   -0.019954 -0.018566  -0.013855   -0.015522  -0.017878   -0.018405
2015-12-09   -0.005236 -0.010863  -0.012082   -0.007580  -0.020258   -0.005147
2015-12-10    0.005848 -0.003030   0.007747    0.002291   0.001498    0.004065
2015-12-11   -0.027326 -0.029250  -0.030476   -0.023472  -0.040096   -0.018955
2015-12-14    0.004184 -0.000196  -0.000906    0.003122  -0.006234   -0.002063
2015-12-15    0.036905  0.027789   0.031803    0.028474   0.030113    0.032143
2015-12-16    0.018944  0.026276   0.023076    0.021634   0.023447    0.017119
2015-12-17   -0.025352 -0.019666  -0.019333   -0.018510  -0.036596   -0.006804
2015-12-18   -0.031214 -0.030848  -0.038990   -0.028364  -0.033663   -0.030287
2015-12-21    0.012530  0.011326   0.012878    0.017702   0.012464    0.004276
2015-12-22    0.006482  0.004248   0.012940    0.002136   0.017045    0.005924
2015-12-23    0.015222  0.011921   0.016107    0.015987   0.011794    0.012882
2015-12-24   -0.004037  0.001520  -0.002624   -0.001948  -0.003681   -0.003997
2015-12-28   -0.008107 -0.006261  -0.004658   -0.003303  -0.009544   -0.002554
2015-12-29    0.008757  0.011455   0.010516    0.010395   0.011812    0.011156
2015-12-30   -0.013310 -0.012835  -0.008282   -0.007157  -0.009831   -0.007235
2015-12-31   -0.012903 -0.010516  -0.009780   -0.008410  -0.013031   -0.009656

[2517 rows x 6 columns]